# Generate .env.aws with all credentials for the AWS deployment.
# Usage: docker compose --env-file .env.aws -f docker-compose.local.yml up -d

resource "local_file" "env_aws" {
  filename        = "${path.module}/../.env.aws"
  file_permission = "0600"
  content         = <<-EOF
    # Auto-generated by Terraform — AWS credentials
    # DO NOT commit this file to git

    # --- PostgreSQL (RDS) ---
    POSTGRES_USER=${var.db_username}
    POSTGRES_PASSWORD=${var.db_password}
    POSTGRES_DB=smartlock
    DATABASE_URL=postgresql://${var.db_username}:${var.db_password}@${aws_db_instance.postgres.address}:5432/smartlock

    # --- Redshift (same RDS, second DB) ---
    REDSHIFT_USER=${var.db_username}
    REDSHIFT_PASSWORD=${var.db_password}
    REDSHIFT_DB=smartlock_dw
    REDSHIFT_JDBC_URL=jdbc:postgresql://${aws_db_instance.postgres.address}:5432/smartlock_dw

    # --- Kafka (EC2) ---
    KAFKA_BOOTSTRAP_SERVERS=${aws_instance.kafka.public_ip}:9092

    # --- S3 (real AWS) ---
    AWS_ACCESS_KEY_ID=USE_IAM_ROLE
    AWS_SECRET_ACCESS_KEY=
    AWS_REGION=${var.region}
    S3_ENDPOINT=https://s3.${var.region}.amazonaws.com
    S3_STAGING_BUCKET=${aws_s3_bucket.staging.id}
  EOF
}

resource "local_file" "docker_compose_local" {
  filename = "${path.module}/../docker-compose.local.yml"
  content  = <<-YAML
    # Auto-generated by Terraform — local services only.
    # Kafka, PostgreSQL, and S3 run on AWS.
    #
    # Usage: docker compose --env-file .env.aws -f docker-compose.local.yml up -d

    services:
      api:
        build:
          context: .
          dockerfile: docker/Dockerfile.api
        ports:
          - "8000:8000"
        env_file: .env.aws
        environment:
          KAFKA_BOOTSTRAP_SERVERS: $${KAFKA_BOOTSTRAP_SERVERS}
          DATABASE_URL: $${DATABASE_URL}

      consumer:
        build:
          context: .
          dockerfile: docker/Dockerfile.consumer
        env_file: .env.aws
        environment:
          KAFKA_BOOTSTRAP_SERVERS: $${KAFKA_BOOTSTRAP_SERVERS}
          DATABASE_URL: $${DATABASE_URL}
  YAML
}

data "aws_caller_identity" "current" {}
