FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc librdkafka-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY database.py db_models.py schemas.py ./
COPY kafka/ kafka/

CMD ["python", "-m", "kafka.consumer"]
